config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'
  
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update'
  #get '/recipes/:id', to: 'recipes#show', as: 'show_recipe'
  #delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :recipes do
    member do
      post 'like'
      post 'add_review'
      get 'edit_review'
      patch 'update_review'
      delete 'destroy_review'
    end
  end

  resources :chefs, except: [:new, :destroy]

  resources :styles, :ingredients, only: [:new, :create, :show, :index, :destroy]


  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 2, maximum: 25 }
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :require_user, except: [:show, :index]
	before_action :admin_user, only: [:destroy]

	def index
		@ingredients = Ingredient.paginate(page: params[:page], per_page: 4)
	end

	def new 
		@ingredient = Ingredient.new
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)

	    if @ingredient.save
	      flash[:success] = "Your ingredient was created successfully!"
	      redirect_to ingredients_path
	    else
	      render :new
	    end
	end

	def show
		@ingredient = Ingredient.find(params[:id])
		@recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 4)
	end

	def destroy
		ingredient = Ingredient.find(params[:id])
		if ! ingredient.recipes.any?
			ingredient.destroy
			flash[:success] = "Ingredient Deleted"
    	else
			flash[:danger] = "Ingredient can't be deleted"
		end
    	redirect_to ingredients_path
	end

	private 

    	def ingredient_params
      		params.require(:ingredient).permit(:name)
    	end

end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors',obj: @ingredient %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for(@ingredient, html: { multipart: true }) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
           
            <%= f.submit(@ingredient.new_record? ? 'Create Ingredient' : 'Edit Ingredient', class: "btn btn-success") %>
        <% end %>
    </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class='quiet'><%= link_to ingredient.name, ingredient_path(ingredient) %> </span>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: 'All Ingredients' %>

<ul class="nav nav-tabs">
    <li>
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li>
        <%= link_to "Chefs", chefs_path %>
    </li>
    <li class="active">
        <%= link_to "Ingredients", ingredients_path %>
    </li>
    <li>
        <%= link_to "Styles", styles_path %>
    </li>
</ul>

<%= will_paginate %>

<hr/>
<% if @ingredients.any? %>
    <% @ingredients.each do |ingredient| %>
        <div class="row">
            <h4 class="center"> <%= link_to ingredient.name, ingredient_path(ingredient) %> 
            <% if current_user.admin? and ! ingredient.recipes.any? %> 
                <%= link_to "Delete ingredient", ingredient, method: :delete,  data: {confirm: "Are you sure?"},class: "btn btn-danger" %>
            <% end unless current_user.nil? %>
            </h4>
        </div>
        <hr/>
    <% end %>
<% else %>
    <div class="row">
        <h4 class="center"> Ingredients are empty. </h4>
    </div>
    <hr/>
<% end %>

<%= will_paginate %>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: 'Create a New Ingredient' %>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "Recipes for: " + @ingredient.name %>
<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li>
        <%= link_to "Chefs", chefs_path %>
    </li>
    <li>
        <%= link_to "Ingredients", ingredients_path %>
    </li>
    <li>
        <%= link_to "Styles", styles_path %>
    </li>
</ul>

<%= will_paginate @recipes%>

<hr/>
<% @recipes.each do |recipe| %>
    <div class="row">
        <div class="col-md-2">
            <section class="chef_info center">
                <%= link_to gravatar_for(recipe.chef), chef_path(recipe.chef) %>
                <h5>Chef name: <%= recipe.chef.chefname %></h5>
            </section>
        </div>
        <div class="col-lg-6 well">
            <h4> <%= link_to recipe.name, recipe_path(recipe) %> </h4>
            <p> <%= recipe.summary %></p>
            <p> Styles: <%= render recipe.styles %></p>
            <p> Ingredients: <%= render recipe.ingredients %></p>
            <p>
                <span class='quiet'> <small> created: <%= time_ago_in_words(recipe.created_at) %>,</small></span>
                <span class='quiet'> <small> updated: <%= time_ago_in_words(recipe.updated_at) %></small></span>
            </p>
            <div class="pull-right">
                <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
                <% end %>
            </div>
        </div> 
        <div class="col-md-4">
            <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
        </div>
    </div>
    <hr/>
<% end %>

<%= will_paginate @recipes%>