config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'
  
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update'
  #get '/recipes/:id', to: 'recipes#show', as: 'show_recipe'
  #delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :recipes do
    member do
      post 'like'
      post 'add_review'
      get 'edit_review'
      patch 'update_review'
      delete 'destroy_review'
    end
  end

  resources :chefs, except: [:new, :destroy]

  resources :styles, :ingredients, only: [:new, :create, :show, :index, :destroy]


  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4"> 
                <h3 class="midrow">
                    View Recipes as Guest User
                </h3>
                <h2 class="left"> Browse and view recipes as a guest and Sign up later</h2>
                <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
            </div>
            <div class="col-lg-4"> 
                <h3 class="midrow">
                    Sing in to your account
                </h3>
                <h2 class="left"> Add/update your recipes/create reviews/like-dislike recipes a much much more!</h2>
                <p><%= link_to "Log in in your account", login_path, class: "btn btn-warning btn-small" %></p>
            </div>
            <div class="col-lg-4"> 
                <h3 class="midrow">
                    View Recipes as Guest User
                </h3>
                <h2 class="left"> Browse and view recipes as a guest and Sign ip later</h2>
                <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-12">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %>
                <a class="close" data-dismiss="alert">&#215;</a>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
        <%= link_to "myRecipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
        <ul class='nav-ul-item'>
            <li class='dropdown'>
                <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                    Styles <b class='caret'></b>
                <% end %>
                <ul class='dropdown-menu'>
                    <% Style.all.each do |style| %>
                        <li><%= link_to style.name, style_path(style) %></li>
                    <% end %>
                    <% if logged_in? %>
                        <li class='divider'></li>
                        <li>
                            <%= link_to(new_style_path) do %>
                                New Style
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </li>
        </ul>
        <ul class='nav-ul-item'>
            <li class='dropdown'>
                <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                    Ingredients <b class='caret'></b>
                <% end %>
                <ul class='dropdown-menu'>
                    <% Ingredient.all.each do |ingredient| %>
                        <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
                    <% end %>
                    <% if logged_in? %>
                        <li class='divider'></li>
                        <li>
                            <%= link_to(new_ingredient_path) do %>
                                New Ingredient
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </li>
        </ul>

        <% if logged_in? %>
            <div class='nav-item'>
                <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
            </div>
            <ul class='nav-ul-item'>
                <li class='dropdown'>
                    <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                        <%= current_user.chefname %> <b class='caret'></b>
                    <% end %>
                    <ul class='dropdown-menu'>
                        <li><%= link_to "View profile", chef_path(current_user) %></li>
                        <li><%= link_to "Edit profile", edit_chef_path(current_user) %></li>
                        <li class='divider'></li>
                        <li><%= link_to "Logout", logout_path %></li>
                    </ul>
                </li>
            </ul>
       <% else %>
            <div class='nav-item'>
                <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
            </div>
        <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %> 
    <%= yield %>
  
  </div>
</body>

<%= render 'layouts/footer' %>

</html>